routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\KriteriaController;
use App\Http\Controllers\AlternatifController;
use App\Http\Controllers\AlgoritmaController;
use App\Http\Controllers\CripsController;
use App\Http\Controllers\PenilaianController;
use App\Models\Kriteria;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('kriteria', KriteriaController::class)->except(['create']);
Route::resource('alternatif', AlternatifController::class)->except(['create', 'show']);
Route::resource('crips', CripsController::class)->except(['index', 'create', 'show']);
Route::resource('/penilaian', PenilaianController::class);
// Route::resource('penilaian', 'App\Http\Controllers\PenilaianController');
Route::get('/perhitungan', [AlgoritmaController::class, 'index'])->name('perhitungan.index');
// Route::resource('/perhitungan', 'App\Http\Controllers\AlgoritmaController');
// Route::delete('/kriteria/{id}', 'KriteriaController@destroy');
// Route::get('/kriteria', [KriteriaController::class, 'index']);
// Route::post('/kriteria/store', [KriteriaController::class, 'store']);
// Route::get('/kriteria/edit/{id}', [KriteriaController::class, 'edit']);
// Route::put('/kriteria/update/{id}', [KriteriaController::class, 'update']);
// Route::post('/kriteria/delete/{id}', [KriteriaController::class, 'destroy']);
// Route::get('/','HomeController@index')->name('home');
// Route::get('/kriteria', [App\Http\Controllers\KriteriaController::class, 'index']);
// Route::resource("kriteria", "KriteriaController");
// Route::middleware(['auth'])->controller(KriteriaController::class)->group(function () {
//     Route::resource('kriteria');
// });

app/Models/Kriteria.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Kriteria extends Model
{
    use HasFactory;
    protected $table = 'kriteria';
    protected $guarded = ['id'];

    public function crips()
    {
        return $this->hasMany(Crips::class, 'kriteria_id');
    }
}

app/Http/Controllers/KriteriaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Crips;
use App\Models\Kriteria;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\DB;

class KriteriaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
        $data['kriteria'] = Kriteria::orderBy('nama_kriteria', 'ASC')->get();
        return view('admin.kriteria.index', $data);
    }

    public function store(Request $request)
    {
        // dd($request);
        try{
            DB::beginTransaction();
            $validator = Validator::make($request->all(),[
                'nama_kriteria' => 'required|string',
                'attribut'      => 'required|string',
                'bobot'         => 'required|numeric',
            ]);
    
            if($validator->fails()){
                return back()->with('toast_error', $validator->messages()->all()[0])->withInput();
            }
    
            Kriteria::create([
                'nama_kriteria' => request()->nama_kriteria,
                'attribut' => request()->attribut,
                'bobot' => request()->bobot,
            ]);

            DB::commit();
            return redirect('kriteria')->with('success', 'Kriteria berhasil ditambahkan!');
        }catch(\Exception $e){
            DB::rollback(); 
            return redirect()->back()->with('warning','Something Went Wrong!');
        }
        
    }
    public function edit($id)
    {
        $data['kriteria'] = Kriteria::findOrFail($id);
        return view('admin.kriteria.edit', $data);
    }

    public function update(Request $request, $id)
    {
        try{
            DB::beginTransaction();
            $kriteria = Kriteria::findOrFail($id);
            $validator = Validator::make($request->all(),[
            'nama_kriteria' => 'required|string',
            'attribut'      => 'required|string',
            'bobot'         => 'required|numeric',
            ]);
    
            if($validator->fails()){
                return back()->with('toast_error', $validator->messages()->all()[0])->withInput();
            }
            $kriteria->update([
                'nama_kriteria' => $request->nama_kriteria,
                'attribut' => $request->attribut,
                'bobot' => $request->bobot
            ]);

            DB::commit();
                return back()->with('success', 'Kriteria berhasil diedit!');
            }catch(\Exception $e){
                DB::rollback(); 
                return back()->with('warning','Something Went Wrong!');
            }
    }

    public function destroy($id)
    {
        // $kriteria = Kriteria::findOrFail($id);
        // $kriteria->delete();
        // return redirect()->route('kriteria.index')->with('success', 'Data berhasil dihapus.');
        try{
            DB::beginTransaction();
            $kriteria = Kriteria::findOrFail($id);
            $kriteria->delete();
            DB::commit();
                return back()->with('success', 'Kriteria berhasil dihapus!');
        }   catch(\Exception $e){
                DB::rollback(); 
                return back()->with('warning','Something Went Wrong!');
        }
    }

    public function show($id)
    {
        $data['crips'] = Crips::where('kriteria_id', $id)->get();
        $data['kriteria'] = Kriteria::findOrFail($id);
        return view('admin.kriteria.show', $data);
    }
}

resources/views/admin/kriteria/edit.blade.php
@extends('layouts.app')
@section('title', 'Edit ', $kriteria->nama_kriteria)
@section('content')
    <div class="row">
        <div class="col-md-4">
            <div class="card shadow mb-4">
                <!-- Card Header - Accordion -->
                <a href="#tambahkriteria" class="d-block card-header py-3" data-toggle="collapse"
                    role="button" aria-expanded="true" aria-controls="collapseCardExample">
                    <h6 class="m-0 font-weight-bold text-primary">Edit Kriteria {{ $kriteria->nama_kriteria }}</h6>
                </a>
                <!-- Card Content - Collapse -->
                <div class="collapse show" id="tambahkriteria">
                    <div class="card-body">
                        @if (Session::has('success'))
                        <div class="alert alert-info alert-dismissible fade show" role="alert">
                            <strong>Info!</strong> {{ Session::get('success') }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                        @endif
                        <form action="{{ route('kriteria.update', $kriteria->id) }}" method="post">
                        @csrf
                        @method('put')
                        <div class="form-group">
                            <label for="nama">Nama Kriteria</label>
                            <input type="text" class="form-control @error('nama_kriteria') is-invalid @enderror"
                            name="nama_kriteria" value="{{ $kriteria->nama_kriteria }}" required>
                            @error('nama_kriteria')
                                <div class="invalid-feedback" role="alert">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="nama">Atribut Kriteria</label>
                            <select name="attribut" id="" class="form-control" required>
                                <option {{ $kriteria->attribut == 'Benefit' ? 'selected' : '' }}>Benefit</option>
                                <option {{ $kriteria->attribut == 'Cost' ? 'selected' : '' }}>Cost</option>
                            </select>
                            @error('attribut')
                                <div class="invalid-feedback" role="alert">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="bobot">Bobot Kriteria</label>
                            <input type="text" class="form-control @error('bobot') is-invalid @enderror"
                            name="bobot" value="{{ $kriteria->bobot }}" required>
                            @error('bobot')
                                <div class="invalid-feedback" role="alert">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <button class="btn btn-sm btn-primary">Simpan</button>
                        <a href="{{ route('kriteria.index') }}" class="btn btn-sm btn-success">Kembali</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/kriteria/index.blade.php
@extends('layouts.app')
@section('title', 'SPK SAW | Kriteria')
@section('css')
    <!-- Custom styles for this page -->
    <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endsection
@section('content')
    <div class="row">
        <div class="col-md-4">
            <div class="card shadow mb-4">
                <!-- Card Header - Accordion -->
                <a href="#tambahkriteria" class="d-block card-header py-3" data-toggle="collapse"
                    role="button" aria-expanded="true" aria-controls="collapseCardExample">
                    <h6 class="m-0 font-weight-bold text-primary">Tambah Kriteria</h6>
                </a>
                <!-- Card Content - Collapse -->
                <div class="collapse show" id="tambahkriteria">
                    <div class="card-body">
                        @if (Session::has('success'))
                        <div class="alert alert-info alert-dismissible fade show" role="alert">
                            <strong>Info!</strong> {{ Session::get('success') }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                        @endif
                        <form action="{{ route('kriteria.store') }}" method="post">
                        @csrf
                        <div class="form-group">
                            <label for="nama">Nama Kriteria</label>
                            <input type="text" class="form-control @error('nama_kriteria') is-invalid @enderror"
                            name="nama_kriteria" required>
                            @error('nama_kriteria')
                                <div class="invalid-feedback" role="alert">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="nama">Atribut Kriteria</label>
                            <select name="attribut" id="" class="form-control" required>
                                <option>Benefit</option>
                                <option>Cost</option>
                            </select>
                            @error('attribut')
                                <div class="invalid-feedback" role="alert">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="bobot">Bobot Kriteria</label>
                            <input type="text" class="form-control @error('bobot') is-invalid @enderror"
                            name="bobot" required>
                            @error('bobot')
                                <div class="invalid-feedback" role="alert">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <button class="btn btn-sm btn-primary">Simpan</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="card shadow mb-4">
                <!-- Card Header - Accordion -->
                <a href="#listkriteria" class="d-block card-header py-3" data-toggle="collapse"
                    role="button" aria-expanded="true" aria-controls="collapseCardExample">
                    <h6 class="m-0 font-weight-bold text-primary">List Kriteria</h6>
                </a>
                <!-- Card Content - Collapse -->
                <div class="collapse show" id="listkriteria">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-hover" id="DataTable">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Nama Kriteria</th>
                                        <th>Attribut</th>
                                        <th>Bobot</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($kriteria as $k)
                                        <tr>
                                            <td>{{ $loop->iteration }}</td>
                                            <td>{{ $k->nama_kriteria }}</td>
                                            <td>{{ $k->attribut }}</td>
                                            <td>{{ $k->bobot }}</td>
                                            <td>
                                                <a href="{{ route('kriteria.show', $k->id) }}" class="btn btn-sm btn-circle btn-info">
                                                    <i class="fa fa-eye"></i>
                                                </a>
                                                <a href="{{ route('kriteria.edit', $k->id) }}" class="btn btn-sm btn-circle btn-warning">
                                                    <i class="fa fa-edit"></i>
                                                </a>
                                                 <form action="{{ route('kriteria.destroy', $k->id) }}" method="POST">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-sm btn-circle btn-danger hapus"><i class="fa fa-trash"></i></button>
                                                </form> 
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('js')
    <!-- Page level plugins -->
    <script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('js/sweetalert.js') }}"></script> 
    <script>
        $(document).ready(function() {
            $('#DataTable').DataTable();

            $('.hapus').on('click', function() {
                swal({
                    title: "Apakah kamu yakin?",
                    text: "Sekali kamu hapus, data tidak dapat dikembalikan",
                    icon: "warning",
                    buttons: true,
                    dangerMode: true,
                    })
                    .then((willDelete) => {
                    if (willDelete) {
                        $.ajax({
                            url: (this).attr('href'),
                            type: 'DELETE',
                            data:{
                                '_token': "{{ csrf_token() }}"
                            },
                            success:function() 
                            {
                                swal("Poof! Your imaginary file has been deleted!", {
                                icon: "success",
                                }).then((willDelete) =>{
                                    window.location = "{{ route('kriteria.index') }}"
                                });          
                            }
                        })
                    } else {
                        swal("Data Aman!");
                    }
                    });

                    return false;
            })
        })
</script>
@endsection

resources/views/admin/kriteria/show.blade.php
@extends('layouts.app')
@section('title', 'SPK SAW | ' .$kriteria->nama_kriteria)
@section('css')
    <!-- Custom styles for this page -->
    <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endsection
@section('content')
    <div class="row">
        <div class="col-md-4">
            <div class="card shadow mb-4">
                <!-- Card Header - Accordion -->
                <a href="#tambahcrips" class="d-block card-header py-3" data-toggle="collapse"
                    role="button" aria-expanded="true" aria-controls="collapseCardExample">
                    <h6 class="m-0 font-weight-bold text-primary">Tambah Crips</h6>
                </a>
                <!-- Card Content - Collapse -->
                <div class="collapse show" id="tambahcrips">
                    <div class="card-body">
                        @if (Session::has('success'))
                        <div class="alert alert-info alert-dismissible fade show" role="alert">
                            <strong>Info!</strong> {{ Session::get('success') }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                        @endif
                        <form action="{{ route('crips.store') }}" method="POST">
                        @csrf
                        <input type="hidden" value="{{ $kriteria->id }}" name="kriteria_id">
                        <div class="form-group">
                            <label for="nama">Nama Crips</label>
                            <input type="text" class="form-control @error('nama_crips') is-invalid @enderror"
                            name="nama_crips" value="{{ old('nama_crips') }}" required>
                            @error('nama_crips')
                                <div class="invalid-feedback" role="alert">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="bobot">Bobot Crips</label>
                            <input type="text" class="form-control @error('bobot') is-invalid @enderror"
                            name="bobot" value="{{ old('bobot') }}" required>
                            @error('bobot')
                                <div class="invalid-feedback" role="alert">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <button class="btn btn-sm btn-primary">Simpan</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="card shadow mb-4">
                <!-- Card Header - Accordion -->
                <a href="#listkriteria" class="d-block card-header py-3" data-toggle="collapse"
                    role="button" aria-expanded="true" aria-controls="collapseCardExample">
                    <h6 class="m-0 font-weight-bold text-primary">List Crips</h6>
                </a>
                <!-- Card Content - Collapse -->
                <div class="collapse show" id="listkriteria">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-hover" id="DataTable">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Nama Crips</th>
                                        <th>Bobot</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($crips as $k)
                                        <tr>
                                            <td>{{ $loop->iteration }}</td>
                                            <td>{{ $k->nama_crips }}</td>
                                            <td>{{ $k->bobot }}</td>
                                            <td>
                                                <a href="{{ route('crips.edit', $k->id) }}" class="btn btn-sm btn-circle btn-warning">
                                                    <i class="fa fa-edit"></i>
                                                </a>
                                                 <form action="{{ route('crips.destroy', $k->id) }}" method="POST">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-sm btn-circle btn-danger hapus"><i class="fa fa-trash"></i></button>
                                                </form> 
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('js')
    <!-- Page level plugins -->
    <script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('js/sweetalert.js') }}"></script> 
    <script>
        $(document).ready(function() {
            $('#DataTable').DataTable();

            $('.hapus').on('click', function() {
                swal({
                    title: "Apakah kamu yakin?",
                    text: "Sekali kamu hapus, data tidak dapat dikembalikan",
                    icon: "warning",
                    buttons: true,
                    dangerMode: true,
                    })
                    .then((willDelete) => {
                    if (willDelete) {
                        $.ajax({
                            url: (this).attr('href'),
                            type: 'DELETE',
                            data:{
                                '_token': "{{ csrf_token() }}"
                            },
                            success:function() 
                            {
                                swal("Poof! Your imaginary file has been deleted!", {
                                icon: "success",
                                }).then((willDelete) =>{
                                    window.location = "{{ route('kriteria.show', $kriteria->id) }}"
                                });          
                            }
                        })
                    } else {
                        swal("Data Aman!");
                    }
                    });

                    return false;
            })
        })
</script>
@endsection