routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\KriteriaController;
use App\Http\Controllers\AlternatifController;
use App\Http\Controllers\AlgoritmaController;
use App\Http\Controllers\CripsController;
use App\Http\Controllers\PenilaianController;
use App\Models\Kriteria;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('kriteria', KriteriaController::class)->except(['create']);
Route::resource('alternatif', AlternatifController::class)->except(['create', 'show']);
Route::resource('crips', CripsController::class)->except(['index', 'create', 'show']);
Route::resource('/penilaian', PenilaianController::class);
// Route::resource('penilaian', 'App\Http\Controllers\PenilaianController');
Route::get('/perhitungan', [AlgoritmaController::class, 'index'])->name('perhitungan.index');
// Route::resource('/perhitungan', 'App\Http\Controllers\AlgoritmaController');
// Route::delete('/kriteria/{id}', 'KriteriaController@destroy');
// Route::get('/kriteria', [KriteriaController::class, 'index']);
// Route::post('/kriteria/store', [KriteriaController::class, 'store']);
// Route::get('/kriteria/edit/{id}', [KriteriaController::class, 'edit']);
// Route::put('/kriteria/update/{id}', [KriteriaController::class, 'update']);
// Route::post('/kriteria/delete/{id}', [KriteriaController::class, 'destroy']);
// Route::get('/','HomeController@index')->name('home');
// Route::get('/kriteria', [App\Http\Controllers\KriteriaController::class, 'index']);
// Route::resource("kriteria", "KriteriaController");
// Route::middleware(['auth'])->controller(KriteriaController::class)->group(function () {
//     Route::resource('kriteria');
// });

app/Models/Alternatif.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Alternatif extends Model
{
    use HasFactory;
    protected $table = 'alternatif';
    protected $guarded = [];

    public function penilaian()
    {
        return $this->hasMany(Penilaian::class, 'alternatif_id');
    }
}

app/Http/Controllers/AlternatifController.php
<?php

namespace App\Http\Controllers;

use App\Models\Alternatif;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\DB;

class AlternatifController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
        $data['alternatif'] = Alternatif::orderBy('nama_alternatif', 'ASC')->get();
        return view('admin.alternatif.index', $data);
    }

    public function store(Request $request)
    {
        // dd($request);
        try{
            DB::beginTransaction();
            $validator = Validator::make($request->all(),[
                'nama_alternatif' => 'required|string',
            ]);
    
            if($validator->fails()){
                return back()->with('toast_error', $validator->messages()->all()[0])->withInput();
            }
    
            Alternatif::create([
                'nama_alternatif' => request()->nama_alternatif,
            ]);

            DB::commit();
            return redirect('alternatif')->with('success', 'Alternatif berhasil ditambahkan!');
        }catch(\Exception $e){
            DB::rollback(); 
            return redirect()->back()->with('warning','Something Went Wrong!');
        }
        
    }
    public function edit($id)
    {
        $data['alternatif'] = Alternatif::findOrFail($id);
        return view('admin.alternatif.edit', $data);
    }

    public function update(Request $request, $id)
    {
        try{
            DB::beginTransaction();
            $alternatif = Alternatif::findOrFail($id);
            $validator = Validator::make($request->all(),[
            'nama_alternatif' => 'required|string',
            ]);
    
            if($validator->fails()){
                return back()->with('toast_error', $validator->messages()->all()[0])->withInput();
            }
            $alternatif->update([
                'nama_alternatif' => $request->nama_alternatif,
            ]);

            DB::commit();
                return back()->with('success', 'Alternatif berhasil diedit!');
            }catch(\Exception $e){
                DB::rollback(); 
                return back()->with('warning','Something Went Wrong!');
            }
    }

    public function destroy($id)
    {
        // $kriteria = Alternatif::findOrFail($id);
        // $kriteria->delete();
        // return redirect()->route('kriteria.index')->with('success', 'Data berhasil dihapus.');
        try{
            $alternatif = Alternatif::findOrFail($id);
            $alternatif->delete();
            DB::commit();
                return back()->with('success', 'Alternatif berhasil dihapus!');
        }   catch(\Exception $e){
                DB::rollback(); 
                return back()->with('warning','Something Went Wrong!');
        }
    }
}

resources/views/admin/alternatif/edit.blade.php
@extends('layouts.app')
@section('title', 'Edit ', $alternatif->nama_alternatif)
@section('content')
    <div class="row">
        <div class="col-md-4">
            <div class="card shadow mb-4">
                <!-- Card Header - Accordion -->
                <a href="#tambahalternatif" class="d-block card-header py-3" data-toggle="collapse"
                    role="button" aria-expanded="true" aria-controls="collapseCardExample">
                    <h6 class="m-0 font-weight-bold text-primary">Edit Alternatif {{ $alternatif->nama_alternatif }}</h6>
                </a>
                <!-- Card Content - Collapse -->
                <div class="collapse show" id="tambahalternatif">
                    <div class="card-body">
                        @if (Session::has('success'))
                        <div class="alert alert-info alert-dismissible fade show" role="alert">
                            <strong>Info!</strong> {{ Session::get('success') }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                        @endif
                        <form action="{{ route('alternatif.update', $alternatif->id) }}" method="post">
                        @csrf
                        @method('put')
                        <div class="form-group">
                            <label for="nama">Nama Alternatif</label>
                            <input type="text" class="form-control @error('nama_alternatif') is-invalid @enderror"
                            name="nama_alternatif" value="{{ $alternatif->nama_alternatif }}" required>
                            @error('nama_alternatif')
                                <div class="invalid-feedback" role="alert">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <button class="btn btn-sm btn-primary">Simpan</button>
                        <a href="{{ route('alternatif.index') }}" class="btn btn-sm btn-success">Kembali</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/alternatif/index.blade.php
@extends('layouts.app')
@section('title', 'SPK SAW | Alternatif')
@section('css')
    <!-- Custom styles for this page -->
    <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endsection
@section('content')
    <div class="row">
        <div class="col-md-4">
            <div class="card shadow mb-4">
                <!-- Card Header - Accordion -->
                <a href="#tambahalternatif" class="d-block card-header py-3" data-toggle="collapse"
                    role="button" aria-expanded="true" aria-controls="collapseCardExample">
                    <h6 class="m-0 font-weight-bold text-primary">Tambah Alternatif</h6>
                </a>
                <!-- Card Content - Collapse -->
                <div class="collapse show" id="tambahalternatif">
                    <div class="card-body">
                        @if (Session::has('success'))
                        <div class="alert alert-info alert-dismissible fade show" role="alert">
                            <strong>Info!</strong> {{ Session::get('success') }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                        @endif
                        <form action="{{ route('alternatif.store') }}" method="post">
                        @csrf
                        <div class="form-group">
                            <label for="nama">Nama Alternatif</label>
                            <input type="text" class="form-control @error('nama_alternatif') is-invalid @enderror"
                            name="nama_alternatif" required>
                            @error('nama_alternatif')
                                <div class="invalid-feedback" role="alert">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <button class="btn btn-sm btn-primary">Simpan</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="card shadow mb-4">
                <!-- Card Header - Accordion -->
                <a href="#listkriteria" class="d-block card-header py-3" data-toggle="collapse"
                    role="button" aria-expanded="true" aria-controls="collapseCardExample">
                    <h6 class="m-0 font-weight-bold text-primary">List Alternatif</h6>
                </a>
                <!-- Card Content - Collapse -->
                <div class="collapse show" id="listkriteria">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-hover" id="DataTable">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Nama Alternatif</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($alternatif as $a)
                                        <tr>
                                            <td>{{ $loop->iteration }}</td>
                                            <td>{{ $a->nama_alternatif }}</td>
                                            <td>
                                                <a href="{{ route('alternatif.edit', $a->id) }}" class="btn btn-sm btn-circle btn-warning">
                                                    <i class="fa fa-edit"></i>
                                                </a>
                                                 <form action="{{ route('alternatif.destroy', $a->id) }}" method="POST">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-sm btn-circle btn-danger hapus"><i class="fa fa-trash"></i></button>
                                                </form> 
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('js')
    <!-- Page level plugins -->
    <script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('js/sweetalert.js') }}"></script> 
    <script>
        $(document).ready(function() {
            $('#DataTable').DataTable();

            $('.hapus').on('click', function() {
                swal({
                    title: "Apakah kamu yakin?",
                    text: "Sekali kamu hapus, data tidak dapat dikembalikan",
                    icon: "warning",
                    buttons: true,
                    dangerMode: true,
                    })
                    .then((willDelete) => {
                    if (willDelete) {
                        $.ajax({
                            url: (this).attr('href'),
                            type: 'DELETE',
                            data:{
                                '_token': "{{ csrf_token() }}"
                            },
                            success:function() 
                            {
                                swal("Poof! Your imaginary file has been deleted!", {
                                icon: "success",
                                }).then((willDelete) =>{
                                    window.location = "{{ route('alternatif.index') }}"
                                });          
                            }
                        })
                    } else {
                        swal("Data Aman!");
                    }
                    });

                    return false;
            })
        })
</script>
@endsection