routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\KriteriaController;
use App\Http\Controllers\AlternatifController;
use App\Http\Controllers\AlgoritmaController;
use App\Http\Controllers\CripsController;
use App\Http\Controllers\PenilaianController;
use App\Models\Kriteria;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('kriteria', KriteriaController::class)->except(['create']);
Route::resource('alternatif', AlternatifController::class)->except(['create', 'show']);
Route::resource('crips', CripsController::class)->except(['index', 'create', 'show']);
Route::resource('/penilaian', PenilaianController::class);
// Route::resource('penilaian', 'App\Http\Controllers\PenilaianController');
Route::get('/perhitungan', [AlgoritmaController::class, 'index'])->name('perhitungan.index');
// Route::resource('/perhitungan', 'App\Http\Controllers\AlgoritmaController');
// Route::delete('/kriteria/{id}', 'KriteriaController@destroy');
// Route::get('/kriteria', [KriteriaController::class, 'index']);
// Route::post('/kriteria/store', [KriteriaController::class, 'store']);
// Route::get('/kriteria/edit/{id}', [KriteriaController::class, 'edit']);
// Route::put('/kriteria/update/{id}', [KriteriaController::class, 'update']);
// Route::post('/kriteria/delete/{id}', [KriteriaController::class, 'destroy']);
// Route::get('/','HomeController@index')->name('home');
// Route::get('/kriteria', [App\Http\Controllers\KriteriaController::class, 'index']);
// Route::resource("kriteria", "KriteriaController");
// Route::middleware(['auth'])->controller(KriteriaController::class)->group(function () {
//     Route::resource('kriteria');
// });

app/Models/Crips.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Crips extends Model
{
    use HasFactory;
    protected $table = "crips";
    protected $guarded = [];
}

app/Http/Controllers/CripsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Alternatif;
use App\Models\Crips;
use App\Models\Kriteria;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\DB;

class CripsController extends Controller
{
    // public function __construct()
    // {
    //     $this->middleware('auth');
    // }
    
    // public function index()
    // {
    //     $data['alternatif'] = Alternatif::orderBy('nama_alternatif', 'ASC')->get();
    //     return view('admin.alternatif.index', $data);
    // }

    public function store(Request $request)
    {
        try{
            DB::beginTransaction();
            $validator = Validator::make($request->all(),[
                'nama_crips' => 'required|string',
                'bobot' => 'required|numeric',
            ]);
    
            if($validator->fails()){
                return back()->with('toast_error', $validator->messages()->all()[0])->withInput();
            }
    
            Crips::create([
                'kriteria_id' => request()->kriteria_id,
                'nama_crips' => request()->nama_crips,
                'bobot' => request()->bobot,
            ]);

            DB::commit();
            return back()->with('success', 'Crips berhasil ditambahkan!');
        }catch(\Exception $e){
            DB::rollback(); 
            return redirect()->back()->with('warning','Something Went Wrong!');
        }
        
    }
    public function edit($id)
    {
        $data['crips'] = Crips::findOrFail($id);

        return view('admin.crips.edit', $data);
    }

    public function update(Request $request, $id)
    {
        try{
            DB::beginTransaction();
            $crips = Crips::findOrFail($id);
            $validator = Validator::make($request->all(),[
                'nama_crips' => 'required|string',
                'bobot' => 'required|numeric',
            ]);
    
            if($validator->fails()){
                return back()->with('toast_error', $validator->messages()->all()[0])->withInput();
            }
            $crips->update([
                'nama_crips' => request()->nama_crips,
                'bobot' => request()->bobot,
            ]);

            DB::commit();
                return back()->with('success', 'Crips berhasil diedit!');
            }catch(\Exception $e){
                DB::rollback(); 
                return back()->with('warning','Something Went Wrong!');
            }
    }

    public function destroy($id)
    {
        try{
            $crips = Crips::findOrFail($id);
            $crips->delete();
            DB::commit();
                return back()->with('success', 'Crips berhasil dihapus!');
        }   catch(\Exception $e){
                DB::rollback(); 
                return back()->with('warning','Something Went Wrong!');
        }
    }
}

resources/views/admin/crips/edit.blade.php
@extends('layouts.app')
@section('title', 'SPK SAW | ' .$crips->nama_crips)
@section('css')
    <!-- Custom styles for this page -->
    <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endsection
@section('content')
    <div class="row">
        <div class="col-md-4">
            <div class="card shadow mb-4">
                <!-- Card Header - Accordion -->
                <a href="#tambahcrips" class="d-block card-header py-3" data-toggle="collapse"
                    role="button" aria-expanded="true" aria-controls="collapseCardExample">
                    <h6 class="m-0 font-weight-bold text-primary">Tambah Crips</h6>
                </a>
                <!-- Card Content - Collapse -->
                <div class="collapse show" id="tambahcrips">
                    <div class="card-body">
                        @if (Session::has('success'))
                        <div class="alert alert-info alert-dismissible fade show" role="alert">
                            <strong>Info!</strong> {{ Session::get('success') }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                        @endif
                        <form action="{{ route('crips.update', $crips->id) }}" method="POST">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="nama">Nama Crips</label>
                            <input type="text" class="form-control @error('nama_crips') is-invalid @enderror"
                            name="nama_crips" value="{{ $crips->nama_crips }}" required>
                            @error('nama_crips')
                                <div class="invalid-feedback" role="alert">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="bobot">Bobot Crips</label>
                            <input type="text" class="form-control @error('bobot') is-invalid @enderror"
                            name="bobot" value="{{ $crips->bobot }}" required>
                            @error('bobot')
                                <div class="invalid-feedback" role="alert">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <button class="btn btn-sm btn-primary">Simpan</button>
                        <a href="{{ route('kriteria.index') }}" class="btn btn-sm btn-info">Kembali</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection